### ISSUE TITLE
Why using setTimeout in scheduler

### ISSUE THREAD

**Issue by apiel** [the-drunk-coder/ruffbox#5]
I try to understand your code cause I would like to implement a web sequencer. Why do you need to use JS `setTimeout`? Doesn't Rust have an timer system? Or would this timer need separate thread to don't block the whole Rust process?

Have you thought about using non blocking timer like it is often done on microcontroller? I remember to have used this on esp-open-rtos https://github.com/SuperHouse/esp-open-rtos 
Have a look there: https://en.wikipedia.org/wiki/FreeRTOS#Implementation

> FreeRTOS implements multiple threads by having the host program call a thread tick method at regular short intervals. The thread tick method switches tasks depending on priority and a round-robin scheduling scheme. The usual interval is 1 to 10 milliseconds (1/1000 to 1/100 of a second), via an interrupt from a hardware timer, but this interval is often changed to suit a particular application.

I guess you might still need to somehow trigger the tick on regular interval and for this you might need `setTimeout`.  Or maybe it would be possible to run the Rust code in loop and regurlarly call a `yield()` function to check if a timer is ready.

**Comment by the-drunk-coder** [comment]
Hi, sorry for the incredibly late reply (I was busy with the project that evolved from this). I think when I made this, using Rust's `std::thread` functions didn't really work, so I couldn't do as much as I wanted in pure Rust and had to resort to JS in situations like this. But since then, plenty of time has passed so it'd be interesting to check if I can reduce the amount of JS code.

**Comment by the-drunk-coder** [comment]
If you're still interested in this please let me know :)
